apiVersion: v2
name: securevault-chart
description: Chart Helm unifiée pour l'application microservices SecureVault
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: AYOUBBNG
    email: ayoub@securevault.io