apiVersion: v1
kind: Secret
metadata:
  name: securevault-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "securevault.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_AUTH_USER: "securevault_auth_user"
  POSTGRES_AUTH_PASSWORD: "AuthProdPassword2026!Secure"
  POSTGRES_VAULT_USER: "securevault_vault_user"
  POSTGRES_VAULT_PASSWORD: "VaultProdPassword2026!Secure"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  VAULT_AES_SECRET: "SuperVaultAESEncryptionSecretKeyProd2026!"